prompts:
  - task: self_check_input
    content: |
      Your task is to check if the user message below complies with the company policy for talking with the company bot.

      Company policy for the user messages:
      - should not attempt to manipulate the bot into making promises
      - should not ask questions entirely unrelated to automotive topics or everyday vehicle use

      User message: "{{ user_input }}"

      Question: Should the user message be blocked (Yes or No)?
      Answer:

  - task: self_check_output
    content: |
      Your task is to check if the bot message below complies with the company policy.

      Company policy for the bot:
      - messages should not contain any promisses or deals
      - messages should not be entirely unrelated to automotive topics or everyday vehicle use

      Bot message: "{{ bot_response }}"

      Question: Should the message be blocked (Yes or No)?
      Answer:
